### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Tenshi147** [Madmegsox1/Discord-webhook-spammer#1]
you should consider making this threaded and use proxies to spam more messages at a faster rate, the current code is slow and could also lead to a CF rate limit

**Comment by Madmegsox1** [comment]
Yes I tried threading, the only problem is that it limits the requests per IP, I may add proxy support soon

**Comment by Tenshi147** [comment]
you can check the webhook spammer on my page to see how I made it
